### PR TITLE
 Program to Display chess board

### PR DESCRIPTION
**Pull request by Krishalakhatiwada**

### CODE REVIEW

**Comment by Krishalakhatiwada** [comment]
Why is my program marked as duplicate when there are no other programs in C to display the chess board?

**Comment by PrajwalCH** [comment]
> Why is my program marked as duplicate when there are no other programs in C to display the chess board?

@Krishalakhatiwada 
https://github.com/itsnporg/Hacktoberfest-2021/blob/main/C-Programs/drawChessBoard.c

**Comment by PrajwalCH** [comment]
> Why is my program marked as duplicate when there are no other programs in C to display the chess board?

Your program output
Screenshot_2021-10-02-21-17-29-1

**Comment by Krishalakhatiwada** [comment]
image
It's working fine on my computer.

**Pull request closed without merging**
