### PR TITLE
Create Glitcheffectindex.html

### PR DESCRIPTION
**Pull request by Mr-cypher**

### CODE REVIEW

**Comment by Mr-cypher** [comment]
Js: [](https://github.com/itsnporg/Hacktoberfest-2021/pull/549)

**Comment by PrajwalCH** [comment]
Make a separate folder for your project inside `HTML` folder and then place js and html file there.

**Comment by Mr-cypher** [comment]
Tried doing so but i am getting "File uploads require push access to this repository" Can you create just folder named "Simple Glitch Effect"

**Comment by PrajwalCH** [comment]
> Tried doing so but i am getting "File uploads require push access to this repository" Can you create just folder named "Simple Glitch Effect"
> 
> 

1. Try fetch upstream again
2. Git clone it on your machine
3. Make a folder and move the files there
4. commit and push it
5. Make a pull request from the web.

**Pull request closed without merging**
