### PR TITLE
Create Find_Minimum_in_Rotated Sorted_Array

### PR DESCRIPTION
**Pull request by abhishekprasad2384**

### CODE REVIEW

**Comment by PrajwalCH** [comment]
@abhishekprasad2384 
Add the file extension.

**Comment by abhishekprasad2384** [comment]
File extension added

**Comment by abhishekprasad2384** [comment]
> @abhishekprasad2384 Add the file extension.
You can check now

**Comment by abhishekprasad2384** [comment]
File extension added

**Comment by PrajwalCH** [comment]
@abhishekprasad2384 
Remove space from the file name.

**Comment by abhishekprasad2384** [comment]
Spaces removed

**Pull request closed without merging**
