### PR TITLE
Linked List insertion, traversal and deletion in C

### PR DESCRIPTION
**Pull request by karandeeppotato**
Linked list insertion , deletion and traversal coded in C language.
1) Insertion at beginning, insertion at end, insertion at an index
   and insertion after a node.
2) Deletion at beginning, deletion at end, deletion at an index
   and  delete a node.
3) Traversal from head node to end.

### CODE REVIEW

**Comment by karandeeppotato** [comment]
Hello there, Please merge this into main

**Review by PrajwalCH — COMMENTED** [review]
Things you can do:
1. Make a separate folder for your project inside `C-Programs`and put all of the code there.
2. Extract the `struct Node` and it's related functions prototype on separate header file.
3. Extract the functions on separate .c file and import its header file.
4. And at last import the header file on other.c file for ex `main.c` and use from there.

**Comment by karandeeppotato** [comment]
Yea, i'll surely do it.
Thanks for the review 😄

**Comment by karandeeppotato** [comment]
I am working on it.

**Comment by karandeeppotato** [comment]
@PrajwalCH 
Hi there, I have done the changes as suggested by you.
Kindly review it.

**Comment by PrajwalCH** [comment]
> @PrajwalCH Hi there, I have done the changes as suggested by you. Kindly review it.

1. Create `ll.h` and define `struct Node` and declare it's related functions (not defination).
```c
struct Node{
    int data;
    struct Node * next;
};

void traversal(struct Node * ptr);

// Insert related functions
struct Node * InsertionAtFirst(struct Node * head, int data);
struct Node * InsertionAtIndex(struct Node * head, int data, int index);
struct Node * InsertionAtEnd(struct Node * head, int data);
struct Node * InsertionAfterNode(struct Node * head, struct Node * prevNode, int data);

// Delete related functions
struct Node * DeleteFromFirst(struct Node * head);
struct Node * DeleteFromIndex(struct Node * head, int index);
struct Node * DeleteFromEnd(struct Node * head);
struct Node * DeleteaValue(struct Node * head, int value);
```
2. Create `ll.c' and include `ll.h` header file and define its related functions
```c
#include "ll.h"
// Include others required header files

void traversal(struct Node * ptr)
{
    // code
}

// Insert related functions
struct Node * InsertionAtFirst(struct Node * head, int data)
{
    // code
}

struct Node * InsertionAtIndex(struct Node * head, int data, int index)
{
    // code
}

struct Node * InsertionAtEnd(struct Node * head, int data);
{
    // code
}

struct Node * InsertionAfterNode(struct Node * head, struct Node * prevNode, int data)
{
    // code
}


// Delete related functions
struct Node * DeleteFromFirst(struct Node * head)
{
    // code
}

struct Node * DeleteFromIndex(struct Node * head, int index)
{
    // code
}

struct Node * DeleteFromEnd(struct Node * head)
{
    // code
}

struct Node * DeleteaValue(struct Node * head, int value)
{
    // code
}
```
3. Create `main.c` file and include `ll.h` header file and use it there.

**Comment by karandeeppotato** [comment]
Thanks for the review.
I'll do the mentioned changes.

**Comment by karandeeppotato** [comment]
Please don't close the issue.
I am working on it.
I was busy with some urgent college work. 🙂

**Comment by karandeeppotato** [comment]
Hello @PrajwalCH,
I have done the changes as suggested by you. Please review it.

**Comment by PrajwalCH** [comment]
Delete old files.

**Comment by karandeeppotato** [comment]
I have already deleted them.
It will be helpful if you specify which file you are talking about.

**Comment by karandeeppotato** [comment]
Hello @PrajwalCH,
Are you talking about the `C-Programs/Singly-Linked-List` directory?

**Comment by PrajwalCH** [comment]
> Hello @PrajwalCH,
> Are you talking about the `C-Programs/Singly-Linked-List` directory?
> 

Nope. Your old single files.

**Comment by karandeeppotato** [comment]
Oh.. got it
Actually i have already deleted those files but forgot to commit them😅

**Comment by karandeeppotato** [comment]
Done !
Please review it 
@PrajwalCH

**Comment by karandeeppotato** [comment]
Sir, What about merging the branch ?
Is their any issue in the commit.
I have done everything told by you

@PrajwalCH

**Comment by PrajwalCH** [comment]
Hacktoberfest excluded this repo so PR are no more valid.

**Comment by karandeeppotato** [comment]
Thats sad... Anyways thanks!
Learned a lot while working on this PR😄

**Comment by PrajwalCH** [comment]
> Thats sad... Anyways thanks!
> Learned a lot while working on this PR😄

Yep that's the important thing.

**Pull request closed without merging**
